package org.springboot.mybatis.domain;

import java.util.Date;

public class SUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.latest_update
     *
     * @mbggenerated
     */
    private Date latestUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.is_del
     *
     * @mbggenerated
     */
    private Boolean isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user
     *
     * @mbggenerated
     */
    public SUser(Long id, String userName, String password, Date latestUpdate, Boolean isDel) {
        this.id = id;
        this.userName = userName;
        this.password = password;
        this.latestUpdate = latestUpdate;
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.id
     *
     * @return the value of s_user.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.user_name
     *
     * @return the value of s_user.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.password
     *
     * @return the value of s_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.latest_update
     *
     * @return the value of s_user.latest_update
     *
     * @mbggenerated
     */
    public Date getLatestUpdate() {
        return latestUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.is_del
     *
     * @return the value of s_user.is_del
     *
     * @mbggenerated
     */
    public Boolean getIsDel() {
        return isDel;
    }
}