package org.springboot.mybatis.domain;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.latest_update
     *
     * @mbggenerated
     */
    private Date latestUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_del
     *
     * @mbggenerated
     */
    private Boolean isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    public User(Long id, String userName, String email, String password, Date latestUpdate, Boolean isDel) {
        this.id = id;
        this.userName = userName;
        this.email = email;
        this.password = password;
        this.latestUpdate = latestUpdate;
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.latest_update
     *
     * @return the value of user.latest_update
     *
     * @mbggenerated
     */
    public Date getLatestUpdate() {
        return latestUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_del
     *
     * @return the value of user.is_del
     *
     * @mbggenerated
     */
    public Boolean getIsDel() {
        return isDel;
    }
}