package org.springboot.mybatis.mapper;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.springboot.mybatis.domain.MpUser;

public interface MpUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_user
     *
     * @mbggenerated
     */
    @Delete({
        "delete from mp_user",
        "where UserID = #{userid,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_user
     *
     * @mbggenerated
     */
    @Insert({
        "insert into mp_user (UserID, UserGUID, ",
        "UserName, UserNick, ",
        "UserType, RealName, ",
        "Tel, UserAvatar, ",
        "IsVerifyTel, UserSex, ",
        "UserJob, UserCompany, ",
        "Birthday, UserNameInstitution, ",
        "InstitutionName, TotalIntegral, ",
        "IsInstituAuthentication, BriefIntroduction, ",
        "IsRegisterHere, AddressProvince, ",
        "AddressCity, AddressArea, ",
        "AddressDetailed, IsBlackListUser, ",
        "Note, CreateOn, ",
        "LatestUpdate)",
        "values (#{userid,jdbcType=BIGINT}, #{userguid,jdbcType=VARCHAR}, ",
        "#{username,jdbcType=VARCHAR}, #{usernick,jdbcType=VARCHAR}, ",
        "#{usertype,jdbcType=INTEGER}, #{realname,jdbcType=VARCHAR}, ",
        "#{tel,jdbcType=VARCHAR}, #{useravatar,jdbcType=VARCHAR}, ",
        "#{isverifytel,jdbcType=INTEGER}, #{usersex,jdbcType=INTEGER}, ",
        "#{userjob,jdbcType=VARCHAR}, #{usercompany,jdbcType=VARCHAR}, ",
        "#{birthday,jdbcType=DATE}, #{usernameinstitution,jdbcType=VARCHAR}, ",
        "#{institutionname,jdbcType=VARCHAR}, #{totalintegral,jdbcType=BIGINT}, ",
        "#{isinstituauthentication,jdbcType=INTEGER}, #{briefintroduction,jdbcType=VARCHAR}, ",
        "#{isregisterhere,jdbcType=INTEGER}, #{addressprovince,jdbcType=VARCHAR}, ",
        "#{addresscity,jdbcType=VARCHAR}, #{addressarea,jdbcType=VARCHAR}, ",
        "#{addressdetailed,jdbcType=VARCHAR}, #{isblacklistuser,jdbcType=INTEGER}, ",
        "#{note,jdbcType=VARCHAR}, #{createon,jdbcType=TIMESTAMP}, ",
        "#{latestupdate,jdbcType=TIMESTAMP})"
    })
    int insert(MpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_user
     *
     * @mbggenerated
     */
    int insertSelective(MpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_user
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "UserID, UserGUID, UserName, UserNick, UserType, RealName, Tel, UserAvatar, IsVerifyTel, ",
        "UserSex, UserJob, UserCompany, Birthday, UserNameInstitution, InstitutionName, ",
        "TotalIntegral, IsInstituAuthentication, BriefIntroduction, IsRegisterHere, AddressProvince, ",
        "AddressCity, AddressArea, AddressDetailed, IsBlackListUser, Note, CreateOn, ",
        "LatestUpdate",
        "from mp_user",
        "where UserID = #{userid,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    MpUser selectByPrimaryKey(Long userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_user
     *
     * @mbggenerated
     */
    @Update({
        "update mp_user",
        "set UserGUID = #{userguid,jdbcType=VARCHAR},",
          "UserName = #{username,jdbcType=VARCHAR},",
          "UserNick = #{usernick,jdbcType=VARCHAR},",
          "UserType = #{usertype,jdbcType=INTEGER},",
          "RealName = #{realname,jdbcType=VARCHAR},",
          "Tel = #{tel,jdbcType=VARCHAR},",
          "UserAvatar = #{useravatar,jdbcType=VARCHAR},",
          "IsVerifyTel = #{isverifytel,jdbcType=INTEGER},",
          "UserSex = #{usersex,jdbcType=INTEGER},",
          "UserJob = #{userjob,jdbcType=VARCHAR},",
          "UserCompany = #{usercompany,jdbcType=VARCHAR},",
          "Birthday = #{birthday,jdbcType=DATE},",
          "UserNameInstitution = #{usernameinstitution,jdbcType=VARCHAR},",
          "InstitutionName = #{institutionname,jdbcType=VARCHAR},",
          "TotalIntegral = #{totalintegral,jdbcType=BIGINT},",
          "IsInstituAuthentication = #{isinstituauthentication,jdbcType=INTEGER},",
          "BriefIntroduction = #{briefintroduction,jdbcType=VARCHAR},",
          "IsRegisterHere = #{isregisterhere,jdbcType=INTEGER},",
          "AddressProvince = #{addressprovince,jdbcType=VARCHAR},",
          "AddressCity = #{addresscity,jdbcType=VARCHAR},",
          "AddressArea = #{addressarea,jdbcType=VARCHAR},",
          "AddressDetailed = #{addressdetailed,jdbcType=VARCHAR},",
          "IsBlackListUser = #{isblacklistuser,jdbcType=INTEGER},",
          "Note = #{note,jdbcType=VARCHAR},",
          "CreateOn = #{createon,jdbcType=TIMESTAMP},",
          "LatestUpdate = #{latestupdate,jdbcType=TIMESTAMP}",
        "where UserID = #{userid,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(MpUser record);
}